SELECT 
    MIN(CASE WHEN OCCUPATION = 'DOCTOR' THEN NAME ELSE NULL END) AS DOCTOR,
    MIN(CASE WHEN OCCUPATION = 'PROFESSOR' THEN NAME ELSE NULL END) AS PROFESSOR,
    MIN(CASE WHEN OCCUPATION = 'SINGER' THEN NAME ELSE NULL END) AS SINGER,
    MIN(CASE WHEN OCCUPATION = 'ACTOR' THEN NAME ELSE NULL END) AS ACTOR
FROM (SELECT OCCUPATION, NAME, ROW_NUMBER() OVER (PARTITION BY OCCUPATION ORDER BY NAME) AS rn FROM OCCUPATIONS) as tmp
GROUP BY tmp.rn