SELECT CONCAT(CONCAT(NAME, '('),CONCAT(SUBSTR(OCCUPATION, 1, 1), ')')) AS
FROM OCCUPATIONS
ORDER BY NAME;
SELECT
    CONCAT(CONCAT('There are a total of ', COUNT(*)), CONCAT(CONCAT(' ', LOWER(OCCUPATION)), 's.'))
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION), OCCUPATION;