SELECT CITY, (LENGTH(CITY))
FROM (SELECT CITY, (LENGTH(CITY))
FROM STATION
ORDER BY 2, 1)
WHERE ROWNUM = 1
UNION
SELECT CITY, (LENGTH(CITY))
FROM (SELECT CITY, (LENGTH(CITY))
FROM STATION
ORDER BY 2 DESC, 1
)
WHERE ROWNUM = 1;