# 4시 50분 시작 4시 53분 종료
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT
INNER JOIN FOOD_ORDER
USING (PRODUCT_ID)
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY 3 DESC, 1