# 4시 32분 시작 4시 48분 종료
SELECT
    MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE
JOIN REST_REVIEW
USING (MEMBER_ID)
WHERE MEMBER_NAME IN
    (SELECT
        MEMBER_NAME
    FROM MEMBER_PROFILE
    JOIN REST_REVIEW
    USING (MEMBER_ID)
    GROUP BY MEMBER_NAME
    HAVING COUNT(*) = (
        SELECT
            COUNT(*)
        FROM MEMBER_PROFILE
        JOIN REST_REVIEW
        USING (MEMBER_ID)
        GROUP BY MEMBER_NAME
        ORDER BY COUNT(*) DESC
        LIMIT 1) )
ORDER BY 3, 2