# 4시 23분 시작 4시 31분 종료
SELECT
    A.ANIMAL_ID,
    A.ANIMAL_TYPE,
    A.NAME
FROM ANIMAL_INS A
JOIN ANIMAL_OUTS B
USING (ANIMAL_ID)
WHERE SEX_UPON_INTAKE LIKE ('In%')
    AND (SEX_UPON_OUTCOME LIKE ('Sp%') OR SEX_UPON_OUTCOME LIKE ('Ne%'))
ORDER BY 1