# 11시 17분 시작 11시 48분 종료
#서울 식당 6개 / 리뷰 있는 식당 4개
SELECT
    REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO A
RIGHT OUTER JOIN REST_REVIEW B
USING (REST_ID)
GROUP BY REST_ID
HAVING ADDRESS LIKE ('서울%')
ORDER BY SCORE DESC, FAVORITES DESC