# 3시 2분 시작 3시 9분 종료
SELECT
    CATEGORY,
    PRICE AS MAX_PRICE,
    PRODUCT_NAME
FROM
    (SELECT
        *,
        RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS PRICE_RANK
    FROM FOOD_PRODUCT
    HAVING CATEGORY IN ('과자', '국', '김치', '식용유') ) X
WHERE PRICE_RANK = 1
ORDER BY 2 DESC