# 3시 26분 시작 3시 37분 종료
WITH RECURSIVE CTE AS (
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM + 1
    FROM CTE
    WHERE NUM < 23
)

SELECT
    CTE.NUM AS HOUR,
    IFNULL(X.COUNT, 0) AS COUNT
FROM CTE
LEFT JOIN (
    SELECT
        HOUR(DATETIME) AS HOUR,
        COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME) ) X
ON CTE.NUM = X.HOUR
ORDER BY 1