# 3시 26분 시작 3시 37분 종료
# 3시 26분 시작 3시 37분 종료
WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM CTE
    WHERE HOUR < 23
)

SELECT
    HOUR,
    IFNULL(X.COUNT, 0) AS COUNT
FROM CTE
LEFT JOIN (
    SELECT
        HOUR(DATETIME) AS HOUR,
        COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME) ) X
USING (HOUR)
ORDER BY 1