# 2시 39분 시작 2시 55분 종료
SELECT
    AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY,
    SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK_SALES
JOIN BOOK
USING (BOOK_ID)
JOIN AUTHOR
USING (AUTHOR_ID)
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY 1, 3 DESC