# 0시 50분 시작 0시 56분 종료
SELECT
    APNT_NO,
    PT_NAME,
    PT_NO,
    B.MCDP_CD,
    DR_NAME,
    APNT_YMD
FROM DOCTOR A
LEFT OUTER JOIN APPOINTMENT B
ON A.DR_ID = B.MDDR_ID
INNER JOIN PATIENT C
USING (PT_NO)
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
    AND B.MCDP_CD = 'CS' AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD