# 3시 52분 시작 4시 20분 종료
# 1단계 : 11월 1일부터 11월 30일까지 대여 가능한 세단 또는 suv의 car_id, 타입, 하루요금 추출
WITH STEP1 AS (
SELECT
    CAR_ID,
    CAR_TYPE,
    DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_ID NOT IN
    (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')) # 11월에 대여불가능한 자동차
    AND CAR_TYPE IN ('세단', 'SUV')
)

# 2단계 할인정책 테이블과 결합, 30만 고려, 30일 대여금액 계산

SELECT
    CAR_ID,
    CAR_TYPE,
    # DAILY_FEE,
    # DURATION_TYPE,
    # DISCOUNT_RATE,
    ROUND(DAILY_FEE * 30 * (100-DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
JOIN STEP1
USING (CAR_TYPE)
WHERE DURATION_TYPE = '30일 이상' AND (DAILY_FEE * 30 * (100-DISCOUNT_RATE) / 100 >= 500000 
                                    AND DAILY_FEE * 30 * (100-DISCOUNT_RATE) / 100 < 2000000)
ORDER BY 3 DESC, 2, 1  DESC