# 3시 39분 시작 3시 47분 종료
SELECT C.ID # 3세대 ID
FROM ECOLI_DATA A # 1세대
JOIN ECOLI_DATA B # 2세대~
    ON A.ID = B.PARENT_ID
JOIN ECOLI_DATA C # 3세대~
    ON B.ID = C.PARENT_ID
WHERE A.PARENT_ID IS NULL # 4세대 cut
ORDER BY 1