# 1시 43분 시작 1시 50분 종료
SELECT 
    ID,
    FISH_NAME,
    LENGTH
FROM(
    SELECT
        *,
        RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RANKING
    FROM FISH_INFO
    JOIN FISH_NAME_INFO
    USING (FISH_TYPE)
    ) A
WHERE RANKING = 1
ORDER BY 1