# 11시 31분 시작 11시 51분 종료
SELECT CONCAT('/home/grep/src/', BOARD_ID,  '/',  FILE_ID,  FILE_NAME, FILE_EXT)
    AS FILE_PATH
FROM USED_GOODS_BOARD
RIGHT OUTER JOIN USED_GOODS_FILE
USING (BOARD_ID)
WHERE VIEWS = (
    SELECT MAX(VIEWS)
    FROM USED_GOODS_BOARD
)
ORDER BY FILE_ID DESC