# 6시 53분 시작 7시 09분 종료
SELECT
    FOOD_TYPE,
    REST_ID,
    REST_NAME,
    FAVORITES
FROM (
    SELECT
        FOOD_TYPE,
        REST_ID,
        REST_NAME,
        FAVORITES,
        RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RANKING
    FROM REST_INFO
) X
WHERE RANKING = 1
ORDER BY 1 DESC

# SELECT
#     FOOD_TYPE,
#     REST_ID,
#     REST_NAME,
#     FAVORITES
# FROM REST_INFO
# WHERE FAVORITES IN (SELECT
#                         MAX(FAVORITES) AS FAVORITES
#                      FROM REST_INFO
#                      GROUP BY FOOD_TYPE)
# GROUP BY FOOD_TYPE
# ORDER BY 1 DESC