# 8시 29분 시작
SELECT
    TITLE,
    BOARD_ID,
    REPLY_ID,
    B.WRITER_ID,
    B.CONTENTS,
    DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD A
    INNER JOIN USED_GOODS_REPLY B
    USING (BOARD_ID)
WHERE DATE_FORMAT(A.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY B.CREATED_DATE, TITLE
# 8시 36분 종료