# 9시 16분 시작 9시 30분 종료
SELECT 
    CAR_TYPE,
    COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE ('%통풍시트%')
    OR OPTIONS LIKE ('%열선시트%')
    OR OPTIONS LIKE ('%가죽시트%')
GROUP BY CAR_TYPE
ORDER BY 1