# 23시 31분 시작  00시 01분 종료

SELECT
    YEAR,
    MONTH,
    PUCHASED_USERS,
    ROUND(PUCHASED_USERS/USER_2021,1) AS PURCHASED_RATIO
FROM(
SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PUCHASED_USERS,
    (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021) AS USER_2021
FROM USER_INFO
JOIN ONLINE_SALE
USING (USER_ID)
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
) A
ORDER BY 1, 2