# https://school.programmers.co.kr/learn/courses/30/lessons/131533

SELECT PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE AS O 
LEFT JOIN PRODUCT AS P
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC
