# 9시 59분 시작 10시 3분 종료
SELECT
    SUM(SCORE) AS SCORE,
    EMP_NO,
    EMP_NAME,
    POSITION,
    EMAIL
FROM HR_DEPARTMENT
JOIN HR_EMPLOYEES
USING (DEPT_ID)
JOIN HR_GRADE
USING (EMP_NO)
WHERE YEAR = 2022
GROUP BY EMP_NO
ORDER BY SUM(SCORE) DESC
LIMIT 1